import ChatsSideBar from "@/components/shared/inbox/ChatsSideBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <main className="bg-[#f5f6fa] font-sans text-gray-800">
      <div className="flex h-screen overflow-hidden">
        <ChatsSideBar />
        {children}
      </div>
    </main>
  );
}
