
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
            <div className="bg-white dark:bg-gray-900 text-gray-900 dark:text-gray-100">
                {children}
            </div>
        </>
  );
}
