import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import ReduxProvider from "@/state/reducers/ReduxProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body
        >
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
